google.maps.__gjsload__('geometry', function(_){var tr=function(a,b){return Math.abs(_.yc(b-a,-180,180))},ur=function(a,b,c,d,e){if(!d){c=tr(a.lng(),c)/tr(a.lng(),b.lng());if(!e)return e=Math.sin(_.Pb(a.lat())),e=Math.log((1+e)/(1-e))/2,b=Math.sin(_.Pb(b.lat())),_.Qb(2*Math.atan(Math.exp(e+c*(Math.log((1+b)/(1-b))/2-e)))-Math.PI/2);a=e.fromLatLngToPoint(a);b=e.fromLatLngToPoint(b);return e.fromPointToLatLng(new _.N(a.x+c*(b.x-a.x),a.y+c*(b.y-a.y))).lat()}e=_.Pb(a.lat());a=_.Pb(a.lng());d=_.Pb(b.lat());b=_.Pb(b.lng());c=_.Pb(c);return _.yc(_.Qb(Math.atan2(Math.sin(e)*
Math.cos(d)*Math.sin(c-b)-Math.sin(d)*Math.cos(e)*Math.sin(c-a),Math.cos(e)*Math.cos(d)*Math.sin(a-b))),-90,90)},vr=_.l(),wr={containsLocation:function(a,b){var c=_.yc(a.lng(),-180,180),d=!!b.get("geodesic"),e=b.get("latLngs"),f=b.get("map");f=!d&&f?f.getProjection():null;for(var g=!1,h=0,k=e.getLength();h<k;++h)for(var m=e.getAt(h),p=0,q=m.getLength();p<q;++p){var t=m.getAt(p),w=m.getAt((p+1)%q),u=_.yc(t.lng(),-180,180),v=_.yc(w.lng(),-180,180),y=Math.max(u,v);u=Math.min(u,v);(180<y-u?c>=y||c<u:
c<y&&c>=u)&&ur(t,w,c,d,f)<a.lat()&&(g=!g)}return g||wr.isLocationOnEdge(a,b)}};_.Xa("PolyGeometry.containsLocation",wr.containsLocation);
wr.isLocationOnEdge=function(a,b,c){c=c||1E-9;var d=_.yc(a.lng(),-180,180),e=b instanceof _.bh,f=!!b.get("geodesic"),g=b.get("latLngs");b=b.get("map");b=!f&&b?b.getProjection():null;for(var h=0,k=g.getLength();h<k;++h)for(var m=g.getAt(h),p=m.getLength(),q=e?p:p-1,t=0;t<q;++t){var w=m.getAt(t),u=m.getAt((t+1)%p),v=_.yc(w.lng(),-180,180),y=_.yc(u.lng(),-180,180),B=Math.max(v,y),D=Math.min(v,y);if(v=1E-9>=Math.abs(_.yc(v-y,-180,180))&&(Math.abs(_.yc(v-d,-180,180))<=c||Math.abs(_.yc(y-d,-180,180))<=
c)){v=a.lat();y=Math.min(w.lat(),u.lat())-c;var E=Math.max(w.lat(),u.lat())+c;v=v>=y&&v<=E}if(v)return!0;if(180<B-D?d+c>=B||d-c<=D:d+c>=D&&d-c<=B)if(w=ur(w,u,d,f,b),Math.abs(w-a.lat())<c)return!0}return!1};_.Xa("PolyGeometry.isLocationOnEdge",wr.isLocationOnEdge);var xr={computeHeading:function(a,b){var c=_.fd(a),d=_.gd(a);a=_.fd(b);b=_.gd(b)-d;return _.yc(_.Qb(Math.atan2(Math.sin(b)*Math.cos(a),Math.cos(c)*Math.sin(a)-Math.sin(c)*Math.cos(a)*Math.cos(b))),-180,180)}};_.Xa("Spherical.computeHeading",xr.computeHeading);
xr.computeOffset=function(a,b,c,d){b/=d||6378137;c=_.Pb(c);var e=_.fd(a);a=_.gd(a);d=Math.cos(b);b=Math.sin(b);var f=Math.sin(e);e=Math.cos(e);var g=d*f+b*e*Math.cos(c);return new _.P(_.Qb(Math.asin(g)),_.Qb(a+Math.atan2(b*e*Math.sin(c),d-f*g)))};_.Xa("Spherical.computeOffset",xr.computeOffset);
xr.computeOffsetOrigin=function(a,b,c,d){c=_.Pb(c);b/=d||6378137;d=Math.cos(b);var e=Math.sin(b)*Math.cos(c);b=Math.sin(b)*Math.sin(c);c=Math.sin(_.fd(a));var f=e*e*d*d+d*d*d*d-d*d*c*c;if(0>f)return null;var g=e*c+Math.sqrt(f);g/=d*d+e*e;var h=(c-e*g)/d;g=Math.atan2(h,g);if(g<-Math.PI/2||g>Math.PI/2)g=e*c-Math.sqrt(f),g=Math.atan2(h,g/(d*d+e*e));if(g<-Math.PI/2||g>Math.PI/2)return null;a=_.gd(a)-Math.atan2(b,d*Math.cos(g)-e*Math.sin(g));return new _.P(_.Qb(g),_.Qb(a))};
_.Xa("Spherical.computeOffsetOrigin",xr.computeOffsetOrigin);xr.interpolate=function(a,b,c){var d=_.fd(a),e=_.gd(a),f=_.fd(b),g=_.gd(b),h=Math.cos(d),k=Math.cos(f);b=xr.kf(a,b);var m=Math.sin(b);if(1E-6>m)return new _.P(a.lat(),a.lng());a=Math.sin((1-c)*b)/m;c=Math.sin(c*b)/m;b=a*h*Math.cos(e)+c*k*Math.cos(g);e=a*h*Math.sin(e)+c*k*Math.sin(g);return new _.P(_.Qb(Math.atan2(a*Math.sin(d)+c*Math.sin(f),Math.sqrt(b*b+e*e))),_.Qb(Math.atan2(e,b)))};_.Xa("Spherical.interpolate",xr.interpolate);
xr.kf=function(a,b){var c=_.fd(a);a=_.gd(a);var d=_.fd(b);b=_.gd(b);return 2*Math.asin(Math.sqrt(Math.pow(Math.sin((c-d)/2),2)+Math.cos(c)*Math.cos(d)*Math.pow(Math.sin((a-b)/2),2)))};xr.computeDistanceBetween=function(a,b,c){c=c||6378137;return xr.kf(a,b)*c};_.Xa("Spherical.computeDistanceBetween",xr.computeDistanceBetween);xr.computeLength=function(a,b){b=b||6378137;var c=0;a instanceof _.T&&(a=a.getArray());for(var d=0,e=a.length-1;d<e;++d)c+=xr.computeDistanceBetween(a[d],a[d+1],b);return c};
_.Xa("Spherical.computeLength",xr.computeLength);xr.computeArea=function(a,b){return Math.abs(xr.computeSignedArea(a,b))};_.Xa("Spherical.computeArea",xr.computeArea);xr.computeSignedArea=function(a,b){b=b||6378137;a instanceof _.T&&(a=a.getArray());for(var c=a[0],d=0,e=1,f=a.length-1;e<f;++e)d+=xr.Dj(c,a[e],a[e+1]);return d*b*b};_.Xa("Spherical.computeSignedArea",xr.computeSignedArea);xr.Dj=function(a,b,c){return xr.Ej(a,b,c)*xr.zk(a,b,c)};
xr.Ej=function(a,b,c){var d=[a,b,c,a];a=[];for(c=b=0;3>c;++c)a[c]=xr.kf(d[c],d[c+1]),b+=a[c];b/=2;d=Math.tan(b/2);for(c=0;3>c;++c)d*=Math.tan((b-a[c])/2);return 4*Math.atan(Math.sqrt(Math.abs(d)))};
xr.zk=function(a,b,c){a=[a,b,c];b=[];for(c=0;3>c;++c){var d=a[c],e=_.fd(d);d=_.gd(d);var f=b[c]=[];f[0]=Math.cos(e)*Math.cos(d);f[1]=Math.cos(e)*Math.sin(d);f[2]=Math.sin(e)}return 0<b[0][0]*b[1][1]*b[2][2]+b[1][0]*b[2][1]*b[0][2]+b[2][0]*b[0][1]*b[1][2]-b[0][0]*b[2][1]*b[1][2]-b[1][0]*b[0][1]*b[2][2]-b[2][0]*b[1][1]*b[0][2]?1:-1};var yr={decodePath:function(a){for(var b=_.J(a),c=Array(Math.floor(a.length/2)),d=0,e=0,f=0,g=0;d<b;++g){var h=1,k=0;do{var m=a.charCodeAt(d++)-63-1;h+=m<<k;k+=5}while(31<=m);e+=h&1?~(h>>1):h>>1;h=1;k=0;do m=a.charCodeAt(d++)-63-1,h+=m<<k,k+=5;while(31<=m);f+=h&1?~(h>>1):h>>1;c[g]=new _.P(1E-5*e,1E-5*f,!0)}c.length=g;return c}};_.Xa("PolylineCodec.decodePath",yr.decodePath);
yr.encodePath=function(a){a instanceof _.T&&(a=a.getArray());return yr.Ll(a,function(a){return[Math.round(1E5*a.lat()),Math.round(1E5*a.lng())]})};_.Xa("PolylineCodec.encodePath",yr.encodePath);yr.Ll=function(a,b){for(var c=[],d=[0,0],e,f=0,g=_.J(a);f<g;++f)e=b?b(a[f]):a[f],yr.Qh(e[0]-d[0],c),yr.Qh(e[1]-d[1],c),d=e;return c.join("")};yr.Qh=function(a,b){yr.Ml(0>a?~(a<<1):a<<1,b)};yr.Ml=function(a,b){for(;32<=a;)b.push(String.fromCharCode((32|a&31)+63)),a>>=5;b.push(String.fromCharCode(a+63))};_.x.google.maps.geometry={encoding:yr,spherical:xr,poly:wr};_.n=vr.prototype;_.n.decodePath=yr.decodePath;_.n.encodePath=yr.encodePath;_.n.computeDistanceBetween=xr.computeDistanceBetween;_.n.interpolate=xr.interpolate;_.n.computeHeading=xr.computeHeading;_.n.computeOffset=xr.computeOffset;_.n.computeOffsetOrigin=xr.computeOffsetOrigin;_.Ie("geometry",new vr);});
